<?php

/**
 * Ideal Region fields for category_descriptions.
 * Without _description → text input; with _description → textarea.
 */
return [
    /**
     * Порядок вариантов на карточке шага (слот 1, 2, 3… → ключ поля без префикса stepN_).
     * step1: 1 — горы, 2 — водопады, 3 — озёра, 4 — города.
     * step2: 1 — гулять, 2 — отдыхать, 3 — развлечения, 4 — рестораны.
     */
    'step_slots' => [
        'step1' => ['gory', 'vodopady', 'ozera', 'goroda'],
        'step2' => ['gulyat', 'otdyh', 'razvlecheniya', 'restorany'],
        'step3' => ['aktivnyi', 'srednii', 'spokoinyi'],
        'step4' => ['kultura', 'eda', 'komfort', 'priroda'],
        'step5' => ['odin', 'druzya', 'semya', 'para'],
        'step6' => ['vkusnaya_eda', 'krasivye_vidy', 'vpechatleniya', 'otdohnut'],
        'step7' => ['parki', 'muzei', 'progulki', 'shopping_razvlecheniya'],
    ],

    'steps' => [
        'step1' => 'Какой пейзаж вам нравится',
        'step2' => 'Что вам ближе в отдыхе',
        'step3' => 'Какой темп вам подходит',
        'step4' => 'Что для вас важнее',
        'step5' => 'С кем вы путешествуете',
        'step6' => 'Что вы хотите от поездки',
        'step7' => 'Что вам интереснее',
    ],

    'labels' => [
        'step1_goroda' => 'Города',
        'step1_goroda_description' => 'Города — описание',
        'step1_ozera' => 'Озёра',
        'step1_ozera_description' => 'Озёра — описание',
        'step1_vodopady' => 'Водопады',
        'step1_vodopady_description' => 'Водопады — описание',
        'step1_gory' => 'Горы',
        'step1_gory_description' => 'Горы — описание',

        'step2_restorany' => 'Рестораны',
        'step2_restorany_description' => 'Рестораны — описание',
        'step2_razvlecheniya' => 'Развлечения',
        'step2_razvlecheniya_description' => 'Развлечения — описание',
        'step2_otdyh' => 'Отдых',
        'step2_otdyh_description' => 'Отдых — описание',
        'step2_gulyat' => 'Гулять',
        'step2_gulyat_description' => 'Гулять — описание',

        'step3_aktivnyi' => 'Активный',
        'step3_aktivnyi_description' => 'Активный — описание',
        'step3_srednii' => 'Средний',
        'step3_srednii_description' => 'Средний — описание',
        'step3_spokoinyi' => 'Спокойный',
        'step3_spokoinyi_description' => 'Спокойный — описание',

        'step4_kultura' => 'Культура',
        'step4_kultura_description' => 'Культура — описание',
        'step4_eda' => 'Еда',
        'step4_eda_description' => 'Еда — описание',
        'step4_komfort' => 'Комфорт',
        'step4_komfort_description' => 'Комфорт — описание',
        'step4_priroda' => 'Природа',
        'step4_priroda_description' => 'Природа — описание',

        'step5_odin' => 'Один',
        'step5_odin_description' => 'Один — описание',
        'step5_druzya' => 'Друзья',
        'step5_druzya_description' => 'Друзья — описание',
        'step5_semya' => 'Семья',
        'step5_semya_description' => 'Семья — описание',
        'step5_para' => 'Пара',
        'step5_para_description' => 'Пара — описание',

        'step6_vkusnaya_eda' => 'Вкусная еда',
        'step6_vkusnaya_eda_description' => 'Вкусная еда — описание',
        'step6_krasivye_vidy' => 'Красивые виды',
        'step6_krasivye_vidy_description' => 'Красивые виды — описание',
        'step6_vpechatleniya' => 'Впечатления',
        'step6_vpechatleniya_description' => 'Впечатления — описание',
        'step6_otdohnut' => 'Отдохнуть',
        'step6_otdohnut_description' => 'Отдохнуть — описание',

        'step7_parki' => 'Парки',
        'step7_parki_description' => 'Парки — описание',
        'step7_muzei' => 'Музеи',
        'step7_muzei_description' => 'Музеи — описание',
        'step7_progulki' => 'Прогулки',
        'step7_progulki_description' => 'Прогулки — описание',
        'step7_shopping_razvlecheniya' => 'Шоппинг и развлечения',
        'step7_shopping_razvlecheniya_description' => 'Шоппинг и развлечения — описание',
    ],

    'fields' => [
        'step1_goroda',
        'step1_goroda_description',
        'step1_ozera',
        'step1_ozera_description',
        'step1_vodopady',
        'step1_vodopady_description',
        'step1_gory',
        'step1_gory_description',
        'step2_restorany',
        'step2_restorany_description',
        'step2_razvlecheniya',
        'step2_razvlecheniya_description',
        'step2_otdyh',
        'step2_otdyh_description',
        'step2_gulyat',
        'step2_gulyat_description',
        'step3_aktivnyi',
        'step3_aktivnyi_description',
        'step3_srednii',
        'step3_srednii_description',
        'step3_spokoinyi',
        'step3_spokoinyi_description',
        'step4_kultura',
        'step4_kultura_description',
        'step4_eda',
        'step4_eda_description',
        'step4_komfort',
        'step4_komfort_description',
        'step4_priroda',
        'step4_priroda_description',
        'step5_odin',
        'step5_odin_description',
        'step5_druzya',
        'step5_druzya_description',
        'step5_semya',
        'step5_semya_description',
        'step5_para',
        'step5_para_description',
        'step6_vkusnaya_eda',
        'step6_vkusnaya_eda_description',
        'step6_krasivye_vidy',
        'step6_krasivye_vidy_description',
        'step6_vpechatleniya',
        'step6_vpechatleniya_description',
        'step6_otdohnut',
        'step6_otdohnut_description',
        'step7_parki',
        'step7_parki_description',
        'step7_muzei',
        'step7_muzei_description',
        'step7_progulki',
        'step7_progulki_description',
        'step7_shopping_razvlecheniya',
        'step7_shopping_razvlecheniya_description',
    ],
];
